# Generated by Django 5.2.5 on 2025-08-18 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signature', models.CharField(choices=[('2/4', 'TWOFOUR'), ('3/4', 'THREEFOUR'), ('4/4', 'FOURFOUR'), ('2/2', 'TWOTWO'), ('6/8', 'SIXEIGHT')], default='4/4', max_length=50)),
                ('difficulty', models.CharField(choices=[('Beginner', 'BEGINNER'), ('Intermediate', 'INTERMEDIATE'), ('Advanced', 'ADVANCED')], default='Intermediate', max_length=100)),
                ('instrument', models.CharField(choices=[('Piano', 'PIANO'), ('Cello', 'CELLO'), ('Violin', 'VIOLIN')], default='Piano', max_length=100)),
                ('measure_count', models.IntegerField(default=10, max_length=500)),
                ('beats_per_minute', models.IntegerField(default=1, max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
