# Generated by Django 5.2.5 on 2025-08-22 16:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_scores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='beats_per_minute',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='score',
            name='difficulty',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='Intermediate', max_length=100),
        ),
        migrations.AlterField(
            model_name='score',
            name='instrument',
            field=models.CharField(choices=[('PIANO', 'Piano'), ('CELLO', 'Cello'), ('VIOLIN', 'Violin')], default='Piano', max_length=100),
        ),
        migrations.AlterField(
            model_name='score',
            name='measure_count',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='score',
            name='signature',
            field=models.CharField(choices=[('TWOFOUR', '2/4'), ('THREEFOUR', '3/4'), ('FOURFOUR', '4/4'), ('TWOTWO', '2/2'), ('SIXEIGHT', '6/8')], default='4/4', max_length=50),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=1000)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='music_scores.score')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
